services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - notesnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - notesnet
    depends_on:
      - mongoDB
    restart: always

  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - notesnet
    volumes:
      - mongo-data:/data/db

networks:
  notesnet:
    driver: bridge

volumes:
  mongo-data:
    driver: local
